#!/usr/bin/bash -e


SOURCE="https://arco.istc.cnr.it/polifonia/sparql"
SOURCE_TYPE="sparql"

# Songs
SONG_QUERY="queries/songs.sparql"
SONG_OUT="data-out/full/songs.json"

# Lyrics
LYR_QUERY="queries/lyric-line.sparql"
LYR_OUT="data-out/full/lyric-line.json"
#LYR_OUT=""


# Spatials
SPAT_QUERY="queries/spatial-annotations-rec-process-session.sparql"
SPAT_OUT="data-out/full/spat-rec.json"
#SPAT_OUT=""


# Harmonics
HARM_QUERY="queries/harmonic-annotations.sparql"
HARM_OUT="data-out/full/harmonic.json"

# merged out

DEMO_OUT="data-out/full/kg.json"


# Fetching songs
node build/bot/song-bot.js run -f $SONG_QUERY -s $SOURCE -t $SOURCE_TYPE -o $SONG_OUT

# Produce lyric annotations
node build/bot/lyricline-bot.js run -f $LYR_QUERY -s $SOURCE -t $SOURCE_TYPE -o $LYR_OUT

# Produce spatial annotations
node build/bot/spatial-bot.js run -f $SPAT_QUERY -s $SOURCE -t $SOURCE_TYPE -o $SPAT_OUT

# Produce harmonic annotations
node build/bot/harmonic-bot.js run -f $HARM_QUERY -s $SOURCE -t $SOURCE_TYPE -o $HARM_OUT


# Merge Annotations

node build/bot/merger.js run -l "${LYR_OUT} ${SPAT_OUT} ${HARM_OUT} ${SONG_OUT}" -o $DEMO_OUT

