PREFIX core:  <https://w3id.org/polifonia/ON/core/>
PREFIX pr:    <https://w3id.org/polifonia/resource/>
PREFIX fx:    <http://sparql.xyz/facade-x/ns/>
PREFIX mp:    <https://w3id.org/polifonia/ON/musical-performance/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mc:    <https://w3id.org/polifonia/ON/musical-composition/>
PREFIX xyz:   <http://sparql.xyz/facade-x/data/>
PREFIX mf:    <https://w3id.org/polifonia/ON/musical-feature/>
PREFIX cm:    <https://w3id.org/polifonia/ON/comparative-measure/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT 
  ?harmonicSimIRI 
  ?recordingAIRI 
#  ?recordingBIRI #          <= How getting this ? 
  ?chordProgressionAIRI 
#  ?chordProgressionBIRI #    <= How getting this ?
  ?simScore
  ?beginCPA 
  ?endCPA
WHERE {  
    ?recordingAIRI  a mp:Recording ;
                    cm:isRecordingInvolvedInCPSim ?CPinSimAIRI ;
                    cm:isRecordingInvolvedInHarmSim ?harmonicSimIRI .

    ?CPinSimAIRI a cm:ChordProgressionInSimilarity ;
                core:hasTimeInterval ?timeIntervalAIRI;
                cm:aboutChordProgression ?chordProgressionAIRI .

    ?timeIntervalAIRI    a core:TimeInterval ;
                            core:startTime ?beginCPA ;
                            core:endTime ?endCPA .

    ?harmonicSimIRI cm:similarityScore ?simScore .


}