PREFIX core:  <https://w3id.org/polifonia/ON/core/>
PREFIX pr:    <https://w3id.org/polifonia/resource/>
PREFIX fx:    <http://sparql.xyz/facade-x/ns/>
PREFIX mp:    <https://w3id.org/polifonia/ON/musical-performance/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX mc:    <https://w3id.org/polifonia/ON/musical-composition/>
PREFIX xyz:   <http://sparql.xyz/facade-x/data/>
PREFIX mf:    <https://w3id.org/polifonia/ON/musical-feature/>
PREFIX cm:    <https://w3id.org/polifonia/ON/comparative-measure/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?harmonicSimIRI ?recordingAIRI ?recordingBIRI ?chordProgressionAIRI ?chordProgressionBIRI ?simScore ?beginCPA ?endCPA
WHERE {  
    ?recordingAIRI  a mp:Recording ;
                    mf:hasChordProgression ?chordProgressionAIRI ;
                    cm:isHarmonicallySimilarTo ?recordingBIRI ;
                    cm:isInvolvedInHarmonicSimilarity ?harmonicSimIRI .
  
    ?chordProgressionAIRI   a mf:ChordProgression ;
                    mf:isChordProgressionOf ?recordingAIRI ;
                    mf:hasStartInRecording ?beginCPA ;
                    mf:hasEndInRecording ?endCPA ;                    
                    cm:isInvolvedInHarmonicSimilarity ?harmonicSimIRI ;
                    cm:hasSimilarChordProgression ?chordProgressionBIRI .

    ?harmonicSimIRI a cm:HarmonicSimilarity ;
                    cm:involves ?recordingAIRI ;
                    cm:involves ?recordingBIRI ;
                    cm:involves ?chordProgressionAIRI ;
                    cm:involves ?chordProgressionBIRI ;
                    cm:hasSimScore ?simScore .
  
      ?chordProgressionAIRI   a mf:ChordProgression ;
                    mf:isChordProgressionOf ?recordingAIRI ;
                    mf:hasStartInRecording ?beginCPA ;
                    mf:hasEndInRecording ?endCPA ;                    
                    cm:isInvolvedInHarmonicSimilarity ?harmonicSimIRI ;
                    cm:hasSimilarChordProgression ?chordProgressionBIRI .
    FILTER(
      ?recordingAIRI != ?recordingBIRI 
      && ?chordProgressionAIRI != ?chordProgressionBIRI
  ) .
}