PREFIX core:  <https://w3id.org/polifonia/ON/core/>
PREFIX pr:    <https://w3id.org/polifonia/resource/>
PREFIX fx:    <http://sparql.xyz/facade-x/ns/>
PREFIX mp:    <https://w3id.org/polifonia/ON/musical-performance/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xyz:   <http://sparql.xyz/facade-x/data/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?recordingID ?recordingTitleLabel ?sessionType ?placeLabel ?placeFullAddress ?placeLat ?placeLong
WHERE {
  ?recordingID rdf:type mp:Recording ;
      core:hasTitle ?title ;
      mp:isRecordingProducedBy ?recordingProcess
  .
  ?title rdfs:label ?recordingTitleLabel.
  ?recordingProcess mp:hasSession ?session.
  ?session core:hasPlace ?place ;
           core:hasType ?sessionType.
  ?place rdfs:label ?placeLabel ;
         core:hasAddress ?placeAddress ;
         core:hasGeometry ?placeGeometry
  .
  ?placeAddress core:fullAddress ?placeFullAddress.
  ?placeGeometry core:lat ?placeLat ;
                 core:long ?placeLong
  .
}