PREFIX core:  <https://w3id.org/polifonia/ON/core/>
PREFIX pr:    <https://w3id.org/polifonia/resource/>
PREFIX fx:    <http://sparql.xyz/facade-x/ns/>
PREFIX mp:    <https://w3id.org/polifonia/ON/musical-performance/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xyz:   <http://sparql.xyz/facade-x/data/>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

SELECT 
?recordingID 
?performerID 
?performerLabel 
?recordingTitleLabel 
?sessionType 
?placeLabel 
?youtubeID
WHERE {
  ?recordingID rdf:type mp:Recording ;
      core:hasTitle ?title ;
      core:hasYoutubeID ?youtubeID2B ;
      mp:hasRecordingPerformer ?performerID ;
      mp:isRecordingProducedBy ?recordingProcess .

      OPTIONAL { ?recordingID core:hasYoutubeID ?youtubeID2B } .
      BIND ( IF (BOUND ( ?youtubeID2B ), ?youtubeID2B, "no_yt_id" )  as ?youtubeID )


  ?title rdfs:label ?recordingTitleLabel.
  ?performerID rdfs:label ?performerLabel.
  ?recordingProcess mp:hasSession ?session.
  ?session core:hasPlace ?place ;
           core:hasType ?sessionType.
  ?place rdfs:label ?placeLabel.
  
}